services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    command: ["tail", "-f", "/dev/null"]

  event_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    command: ["tail", "-f", "/dev/null"]

  chat_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    command: ["tail", "-f", "/dev/null"]
