services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    command: ["python", "user_service/server.py"]

  event_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - .:/app
    command: ["python", "event_service/server.py"]

  chat_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]
